# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IltXssPklLJgQbPQvA2nF6Dj76ms4S4F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Sample data creation
years = range(2010, 2021)
countries = ['USA', 'China', 'India', 'Russia']

# Let's focus on CO2 Emissions and GDP (energy efficiency)
indicators = ['CO2 Emissions', 'GDP']

data = {
    'Year': np.random.choice(years, 40),
    'Country': np.random.choice(countries, 40),
    'CO2 Emissions': np.random.uniform(1000, 5000, 40),
    'GDP': np.random.uniform(1e9, 1e13, 40)  # Assuming GDP values
}

# Create DataFrame
df = pd.DataFrame(data)

# Selecting two countries for comparison
country1 = 'USA'
country2 = 'China'

# Statistical properties of indicators for each country
for country in [country1, country2]:
    country_data = df[df['Country'] == country]
    print(f"Statistics for {country}:")
    print(country_data.describe())
    print()

# Comparison of CO2 Emissions and GDP across countries with trend lines
plt.figure(figsize=(12, 6))
for country in [country1, country2]:
    country_data = df[df['Country'] == country]
    plt.scatter(country_data['GDP'], country_data['CO2 Emissions'], label=country)
    z = np.polyfit(country_data['GDP'], country_data['CO2 Emissions'], 1)
    p = np.poly1d(z)
    plt.plot(country_data['GDP'], p(country_data['GDP']), linestyle='dashed')
plt.xlabel('GDP (Energy Efficiency)')
plt.ylabel('CO2 Emissions')
plt.title('CO2 Emissions vs. GDP')
plt.legend()
plt.grid(True)
plt.show()

# Histograms for CO2 Emissions and GDP
plt.figure(figsize=(8, 6))
plt.subplot(2, 1, 1)
plt.title('Histogram of CO2 Emissions')
sns.histplot(df['CO2 Emissions'], bins=10, kde=True)
plt.xlabel('CO2 Emissions')
plt.ylabel('Frequency')
plt.grid(True)

plt.subplot(2, 1, 2)
plt.title('Histogram of GDP')
sns.histplot(df['GDP'], bins=10, kde=True)
plt.xlabel('GDP (Energy Efficiency)')
plt.ylabel('Frequency')
plt.grid(True)
plt.tight_layout()
plt.show()

# Pairplot to explore relationships between CO2 Emissions and GDP
sns.pairplot(df[['CO2 Emissions', 'GDP']])
plt.suptitle('Pairplot of CO2 Emissions and GDP', y=1.02)
plt.show()